let JohnDoe: Sprite = null
let projectile: Sprite = null
let mySprite: Sprite = null
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    scene.setBackgroundColor(9)
    JohnDoe = sprites.create(img`
        .......ff...............
        ....ffff2ff.............
        ..ffeeeef2ff............
        .ffeeeeef22ff...........
        .feeeeffeeeef...........
        .fffffee2222ef..........
        fffe222ffffe2f..........
        ffffffffeeefff..........
        fefe44ebf44eef..........
        .fee4d4bfddef..f........
        ..feee4dddee.2fffff.....
        ...f2222eeddeffffff22222
        ...f444e44ddef2.f.......
        ...fffffeeee.fff........
        ..ffffffff...ff.........
        ..fff..ff....ffff.......
        .............ffff.......
        .............ffff.......
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Player)
    controller.moveSprite(JohnDoe, 100, 100)
    JohnDoe.setStayInScreen(true)
    projectile = sprites.createProjectileFromSprite(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, mySprite, 30, 30)
})
game.onUpdateInterval(500, function () {
    let myfood: Sprite = null
    JohnDoe = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    myfood.setPosition(0, 0)
    mySprite.setPosition(0 + 0, randint(2, 12))
})
